### PR TITLE
Add action key support for enter to the Readme

### PR DESCRIPTION
**Pull request by TristanCacqueray**

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
Hi, thank you for making this library, it is working great! I think this PR can be useful for newcomers since it is a common usage for navigation.

**Comment by nicopap** [comment]
Thank you for the PR. I'll check it out soonish. It looks good, I'll probably merge it tomorrow.

**Comment by nicopap** [comment]
Just so you know, this doesn't pass the tests when running `cargo test`. Could you fix it?

**Comment by TristanCacqueray** [comment]
Oops sure, let me check that. May I propose a CI job to prevent that in the future?

**Comment by nicopap** [comment]
It's merged but I did mess it up and github didn't pick it up. You still have the name on the commit though.

**Comment by TristanCacqueray** [comment]
Thank you again for designing `ui-navigation`, it's really well thought out and quite a must have quality of life improvement. I just finished using it for my game and it is working great :)

**Pull request closed without merging**
